MOSIP-33679 Inji verify - Automation scripts for UI test cases
mosip/inji-verify pull request #88
Opened 2024-06-14 09:20 UTC by anup-nehe

Inji verify - Automation scripts for UI test cases

2024-06-14 09:37 UTC, lsivanand approved these changes

2024-06-20 09:56 UTC, mohanachandran-s requested changes

2024-06-20 09:56 UTC, mohanachandran-s commented on inji-verify-test/src/test/java/utils/BaseTest.java
> +		driver.getPage().navigate("https://injiverify.qa-inji.mosip.net/");
Reading the URL from config file is getting overridden. Please correct it.

2024-06-20 09:56 UTC, mohanachandran-s commented on inji-verify-test/src/test/java/utils/BaseTest.java
> -
Don't delete these lines as these are required to read the url's from config file.

2024-06-20 09:56 UTC, mohanachandran-s commented on inji-verify-test/src/test/java/utils/BaseTestUtil.java
Don't delete this file

2024-06-20 09:56 UTC, mohanachandran-s commented on inji-verify-test/src/test/resources/config.json
Don't delete this file as well

2024-06-20 09:56 UTC, mohanachandran-s commented on inji-verify-test/src/test/resources/featurefiles/UploadQRCodepage.feature
> +		And Verify that upload QR Code tab is visible
Please correct the indentation

2024-06-20 09:56 UTC, mohanachandran-s commented on inji-verify-test/src/test/resources/featurefiles/scanQRcode.feature
> +		And Verify that Upload button visible
Correct the indentation

2024-06-25 04:26 UTC, mohanachandran-s approved these changes

2024-06-25 08:52 UTC, challabeehyv approved these changes

2024-06-25 08:52 UTC, merged